name: 'Dependency Review'
on: [pull_request]

# https://github.com/actions/dependency-review-action

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4.1.7
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
