name: mypy

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Running mypy
        run: |
          echo 'args = {}' > config.py
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade poetry
          poetry install
          poetry run mypy $(basename $(pwd) | sed -E 's/-/_/g') tests/
