---
name: Python type checking

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy: # don't rename, is referred to in branch rules etc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Running type checking
        run: |
          echo 'args = {}' > config.py
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run ty check
