name: pylint

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint: # don't rename, is referred to in branch rules etc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Running tests
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run ruff check
          uv run validate-pyproject pyproject.toml
